spring:
  application:
    name: security-05-login-info

  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

  datasource:
    url: jdbc:mysql://localhost:3306/dc_security?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: Dingtong1998
    driver-class-name: com.mysql.cj.jdbc.Driver

  mybatis:
    configuration:
      map-underscore-to-camel-case: true
